version: '2'
services: 
    rospider:
        #image: osrf/ros:melodic-desktop-full
        build:
            context: .
        user: "1000:1000"
        container_name: rospider
        environment: 
          - "DISPLAY=$DISPLAY"
          - "QT_X11_NO_MITSHM=1"
          - "TERM=xterm-256color" 
        volumes: 
          - "/home/$USER:/home/HOST"
            #  - "/etc/group:/etc/group:ro"
            #  - "/etc/passwd:/etc/passwd:ro"
            #  - "/etc/shadow:/etc/shadow:ro"
          - "/etc/sudoers.d:/etc/sudoers.d:ro"
          - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        #devices: 
        #- "/dev/ttyUSB0:/dev/ttyUSB0"
        tty: true
        stdin_open: true
