version: '3'
services: 
    myhumble:
        build:
            context: .
        container_name: myhumble
        environment: 
          - "DISPLAY=$DISPLAY"
          - "QT_X11_NO_MITSHM=1"
          - "TERM=xterm-256color" 
        volumes: 
          - "/home/$USER:/home/HOST"
          - "/etc/sudoers.d:/etc/sudoers.d:ro"
          - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
          - "../catkin_ws:/home/docker/catkin_ws"
          - "../colcon_ws:/home/docker/colcon_ws"
        devices: 
          - "/dev/dri:/dev/dri"
          - "/dev/input:/dev/input"
        #  - "/dev/ttyUSB0:/dev/ttyUSB0"
        tty: true
        stdin_open: true
        network_mode: "host"
        
